# Generated by Django 5.0.6 on 2024-06-09 13:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendMusicPlayerApp', '0002_alter_track_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='track',
            new_name='Song',
        ),
    ]
