# Generated by Django 5.0.6 on 2024-06-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendMusicPlayerApp', '0003_rename_track_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist_name',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='author',
            new_name='user',
        ),
    ]
