# Generated by Django 5.0.6 on 2024-06-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendMusicPlayerApp', '0004_rename_artist_name_song_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.URLField(),
        ),
    ]
